### ISSUE TITLE
v7.0.0 release preperation

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1015]
## Summary

Everything we need to do to get the v7.0.0 release ready to go.

## Tasks

- [x] Rename `master` to v6
- [x] Rename v7 to `main`
- [x] Ensure branch protections for `main` are reasonable
- [x] Make sure CircleCI is set up for main not master
- [x] Get netlify building/deploying `main` (currently building `v7`)
- [x] Audit history / issues for confidential things
- [x] Kill off irrelevant issues
- [x] Make repo public
- [ ] Automate releases (#1004)

**Comment by marcelltoth** [comment]
Release management is tracked separately so this is complete.
