### ISSUE TITLE
[spike] Simplify http-spec > HAR & fetch() with fetch-har() or similar

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1357]
## Summary

In the past we did a three stepped conversion from http-spec to HAR to fetch() for Request Sample and Try it, now we convert to both separately. This can lead to discrepancies in the process and at best means we have to do similar things twice. Let's see if [fetch-har](https://www.npmjs.com/package/fetch-har) can simplify the process, by letting us just to http-spec > HAR, then passing this HAR to built up the fetch request.

## Tasks

- [ ] Find out if fetch-har works everywhere we need it to for Elements (e.g.: browser, electron).
- [ ] Does fetch-har magically pass the test suite when we delete all our conversion code and plop this one in?
- [ ] Figure out if we need to send any pull requests or fork it to get it working.
- [ ] Are there any alternative packages that would work better.
