### ISSUE TITLE
Switch to ESlint

### ISSUE THREAD

**Issue by lott-ai** [stoplightio/elements#167]
**Chore summary**

TSLint is deprecated so let's switch over to ESLint

**Tasks**
- [x] Follow the instructions to install Stoplight's ESLint config: https://github.com/stoplightio/eslint-config
- [x] Remove all TSLint dependencies
- [x] Fix any ESLint errors

**Additional context**

- Here's the PR where Studio switched to ESLint which can be used for reference: https://github.com/stoplightio/studio-internal/pull/1479
