### ISSUE TITLE
Investigate using @zeit/swr

### ISSUE THREAD

**Issue by lott-ai** [stoplightio/elements#168]
**Chore summary**

We have a custom hook for managing request data: https://github.com/stoplightio/elements/blob/master/src/hooks/useRequest.tsx. It works fine, but it would be nice to not worry about having to maintaining it.

I found this repo the other day which looks promising but still need to investigate if it will fit all of our needs: https://github.com/zeit/swr

**Tasks**
- [x] Checkout the docs for @zeit/swr: https://github.com/zeit/swr
- [ ] Try using that library instead of our custom `useRequest` hook: https://github.com/stoplightio/elements/blob/master/src/hooks/useRequest.tsx

**Additional context**

- [ ] Needs to support making paginated requests to the /project.nodes endpoint
- [x] Needs to support client side caching of request/response data
