### ISSUE TITLE
Update @stoplight/types to v11

### ISSUE THREAD

**Issue by lott-ai** [stoplightio/elements#21]
**Chore summary**

Review the breaking changes from https://github.com/stoplightio/types/pull/50 and update the relevant locations

**Tasks**
- [x] Update @stoplight/types to the latest 11.x release and any required changes
- [x] Update `studio-internal` when the change from this PR is merged
- [x] Update `app-gen3` when the change from this PR is merged
