### ISSUE TITLE
Bundle FontAwesome icons with Elements

### ISSUE THREAD

**Issue by lott-ai** [stoplightio/elements#525]
## Summary

We're trying to move away from Blueprint and going all in on FontAwesome's free version. We also want to abstract away the fact that we're using FontAwesome, meaning we don't want to require end consumers install the FontAwesome library themselves or add the fontawesome script to their HTML.

Basically we want to be able to remove this statement from our examples:

![image](https://user-images.githubusercontent.com/7423098/92953841-094afd00-f428-11ea-8edb-812977328a34.png)

## Tasks

- [x] Somehow bundle the fontawesome icons into Elements, so the user doesn't need to install them separately. Strategy TBD.
- [x] Update all the example CSS to not load the FontAwesome web font
- [x] Update all the documentation for examples to remove the "You must install FontAwesome blaw blaw" statements
