### ISSUE TITLE
Elements v6 - Phase 2 (Epic)

### ISSUE THREAD

**Issue by billiegoose** [stoplightio/elements#535]
- [x] scope CSS & add bundle CSS export
- [x] finalize what is exported from the root index
- [x] finalize component naming convention
 - - [x] investigate common naming patterns with container/components
- [x] finalize typescript interfaces (prep for http api)
- [x] Boilerplate Gatsby example using StoplightProject react component
- [x] Boilerplate Angular example using StoplightProject web-component
