### ISSUE TITLE
Finalize component naming convention

### ISSUE THREAD

**Issue by lott-ai** [stoplightio/elements#537]
## Summary

Before we can finalize the public API, we need to finalize how the components are named.

## Tasks

- [x] Investigate common naming patterns for the container/component approach
- [x] Propose the name changes in a comment so we can all agree on them
- [ ] Make the necessary changes to our component names in a PR
