### ISSUE TITLE
Finalize root export

### ISSUE THREAD

**Issue by lott-ai** [stoplightio/elements#538]
## Summary

Part of finalizing the public API involves determining what components we want to expose from the root export

## Tasks

- [ ] Investigate our ecosystem to figure out what components we're currently using in Platform, Studio and Gatsby sites (BigCommerce & Qualtrics)
- [ ] Comment on this issue with a proposal for what we should export from the root
- [ ] Make the relevant changes to the elements package: https://github.com/stoplightio/elements/blob/c5e1937bb097a9c6b817694bea743c93acd204ff/packages/elements/src/index.ts#L7
- [ ] Make the relevant changes to the elements-web-components package: https://github.com/stoplightio/elements/blob/aebc77a4c70d8af9c9dd4b80496855ce56ec03c6/packages/elements-web-components/src/index.ts#L4

## Additional context

Add any other context about the chore here.
