### ISSUE TITLE
Investigate common patterns for example demos

### ISSUE THREAD

**Issue by lott-ai** [stoplightio/elements#541]
## Summary

We're currently developing/maintaining two example apps that demonstrate usage of the react and web component libraries.

- Angular Web Components example https://github.com/stoplightio/elements/issues/526
- Gatsby React Components example https://github.com/stoplightio/elements/issues/536

But we need to decide where these examples should live. Here are some considerations:

- Needs to be easy for someone to run the example using the latest source code so we can sanity check them in PRs and while developing
- Needs to be easy for someone to copy the example as a starting point for their own implementation

## Tasks

- [x] Investigate other open source libraries to see where their examples are stored
- [x] Investigate common patterns for Gatsby boilerplate examples
- [x] Investigate common patterns for Web component examples
- [x] Comment on this issue with the proposal for us to agree on
- [x] Agree on proposal
