### ISSUE TITLE
Add icons support to TableOfContents component

### ISSUE THREAD

**Issue by lott-ai** [stoplightio/elements#66]
Currently our TableOfContents component doesn't support icons. We should support passing an icon mapping to the Provider and/or adding an icon directly to the contents items:

**Example:**
```tsx
<TableOfContentsComponent
  contents={[
    {
      name: "Personal",
      depth: 0,
      type: "divider",
    },
    {
      name: "My Projects",
      depth: 0,
      icon: "star",
    },
    {
      name: "GitHub",
      depth: 0,
      icon: "github",
    },
    {
      name: "Stoplight Next",
      depth: 0,
      icon: "gitlab",
    },
    {
      name: "SendGrid",
      depth: 0,
      type: "divider"
    },
    {
      name: "GitHub",
      depth: 0,
      icon: "github",
    },
    {
      name: "Stoplight Next",
      depth: 0,
      icon: "gitlab",
    },
    {
      name: "XYZ Corp",
      depth: 0,
      type: "divider"
    },
    {
      name: "GitHub",
      depth: 0,
      icon: "github",
    }
  ]}
/>
```

**Result:**

![image](https://user-images.githubusercontent.com/7423098/66001473-2977eb00-e467-11e9-9b96-a48c9afada32.png)

**Tasks**

- [x] Add an `icons` prop to `IProvider` that is a dictionary of NodeType to IconName: https://github.com/stoplightio/elements/blob/master/src/containers/Provider.tsx#L8
```ts
export interface IProvider {
  host?: string;
  token?: string;
  components?: IComponentMapping;
  icons?: Dictionary<IconName, NodeType>;
}
```

- [x] Add an "IconsContext" to the provider component that defaults to an empty object: https://github.com/stoplightio/elements/blob/master/src/containers/Provider.tsx#L14
- [x] Render the `IconsContext.Provider` with the other providers and pass it the `icons` prop from the `Provider` component: https://github.com/stoplightio/elements/blob/master/src/containers/Provider.tsx#L30-L34
- [x] Add an optional `icon` prop to `IContentsNode`: https://github.com/stoplightio/elements/blob/master/src/types.ts#L33-L38
```ts
export interface IContentsNode {
  name: string;
  depth: number;
  srn?: string;
  type?: 'divider' | 'group';
  icon?: IconName;
}
```
- [x] In the `useComputeToc` hook, get the icons from `const icons = React.useContext(IconsContext)` then when adding a node to the `contents` check to see if there's an icon: https://github.com/stoplightio/elements/blob/master/src/hooks/useComputeToc.tsx#L25
Example:
```ts
contents.push({
  name: "Example",
  depth: 0,
  type: 'group',
  icon: icons[node.type]
});
```
- [x] Pass the icon into the TableOfContentsItem component: https://github.com/stoplightio/elements/blob/master/src/components/TableOfContents.tsx#L99
- [x] If an icon exists, render it to the left of the item's name: https://github.com/stoplightio/elements/blob/master/src/components/TableOfContents.tsx#L180
