### ISSUE TITLE
[spike] Explore quick wins and possible solutions for #814

### ISSUE THREAD

**Issue by marcelltoth** [stoplightio/elements#815]
## Summary

Spike, **time limit**: 1.5 working days.

While #814 is intentionally unbounded, this is a spike for a day and a half, allocated to understanding the Docs codebase & its typings in more depth, coming up with possible solutions, discussing them, and/or implementing some quick wins.

## Tasks

- [ ] Read the Docs codebase to understand the described problem in great detail
- [ ] See if there are some quick wins you can implement within the time limit.
- [ ] Think about full-scale solutions, even if they cannot be done within the time limit.
- [ ] Discuss your findings with the team. The format is up to you, some ideas: schedule a meeting with a tiny presentation, live demo, or share a Draft PR, even a writeup if you feel like that's enough. You will get a feel for the depth of the problem, choose a format that fits our needs.

For quick wins:
  - [ ] If the remaining time frame allows, implement your quick win.

For long term solutions of if you don't have time to implement what the team agreed on:
  - [ ] Document the accepted solution in an issue, and link it to #814.
