### ISSUE TITLE
Dead Code Purge

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#959]
## Summary

We found that a lot of the usages of UI Kit were in "dead code" (code no longer actively used anywhere but still in the repo). See how much dead code you can remove, even though we might not get everything. 

_Try running some unused code detection tools, and a quick visual check of files/components/hooks/utils/etc._

## Tasks

- [ ] Any hooks left we can remove?
- [ ] Everything in utils being actively used?
- [ ] The old Search component is not used, and a new one is coming in #1172
- [ ] Remove generateAPIToc from elements-utils https://github.com/stoplightio/elements/issues/1142
- [ ] Audit package.json files to make sure we don't have unused deps
