### ISSUE TITLE
Refactor packages to elemenents and elements-dev-portal

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#996]
## Summary

Instead of having "elements" contain both API Component and StoplightProject component, and "elements-web-components" distribute them both in a different form, we'd like to move the web component for API Component into "elements" and make a new "elements-dev-portal" package for the StoplightProject component in both wc and non-wc.

## Tasks

- [x] Archive elements-web-component and point folks to "elements" in the README
- [x] Abandon the elements-web-component on NPM
- [ ] Combine elements storybooks for web components and non web components in Chromatic (see chromatic was used for v6 #857)
- [x] Create elements-dev-portal package and submit to NPM

## Additional context

Feel free to split these issues out however you want. Should be done after the elements API component pre-release.
